# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f771bee010e98067181aceae4009cf0bad4c13430cf16f1ab07972304efe0b1a21e4df0673f975809c7dd3dbec89b92d90c3f4d668d529a7a6bddd2d9964535

test:
  secret_key_base: 4d05deb7780515445539c3f1d16f31ffd590f2433a95b3c296b581cf4fcc771f6689f44c84e17099dbeeacb5c8848e7f6f84beb7a0d02ff3c8174f298cd44e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
